---
# Per environment values which override defaults in gql-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: gql-api-dev.hmpps.service.justice.gov.uk
    contextColour: green

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_OAUTH: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    API_BASE_URL_COMMUNITY: https://community-api-secure.test.delius.probation.hmpps.dsd.io
    API_BASE_URL_PRISON: https://api-dev.prison.service.justice.gov.uk
    API_BASE_URL_PRISONERSEARCH: https://prisoner-offender-search-dev.prison.service.justice.gov.uk

# CloudPlatform AlertManager receiver to route promethues alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps_tech_non_prod
